@echo off
cd "assets/minecraft/textures/block/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/colormap/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/environment/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/gui/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/item/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/map/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/misc/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/mob_effect/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/models/armor/"
del *.png
cd ../../../../..
cd "assets/minecraft/textures/painting/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/particle/"
del *.png
cd ../../../..
cd "assets/minecraft/textures/font/"
del *.png
cd ../../../..
python randomize.py